// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package parallelismtests.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the ParallelismTests module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_StartBlockingThreadsIssueBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.IVK_StartBlockingThreadsIssue");
		return builder;
	}

	public static void iVK_StartBlockingThreadsIssue(IContext context)
	{
		iVK_StartBlockingThreadsIssueBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_StopThreadsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.IVK_StopThreads");
		return builder;
	}

	public static void iVK_StopThreads(IContext context)
	{
		iVK_StopThreadsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_TestAsyncPatternBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.IVK_TestAsyncPattern");
		return builder;
	}

	public static void iVK_TestAsyncPattern(IContext context)
	{
		iVK_TestAsyncPatternBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_TestBackgroundLongBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.IVK_TestBackgroundLong");
		return builder;
	}

	public static void iVK_TestBackgroundLong(IContext context)
	{
		iVK_TestBackgroundLongBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_TestBackgroundShortBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.IVK_TestBackgroundShort");
		return builder;
	}

	public static void iVK_TestBackgroundShort(IContext context)
	{
		iVK_TestBackgroundShortBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder parallel_BlockingIssueBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.Parallel_BlockingIssue");
		return builder;
	}

	public static boolean parallel_BlockingIssue(IContext context)
	{
		Object result = parallel_BlockingIssueBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder parallel_SendMessageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.Parallel_SendMessage");
		return builder;
	}

	public static parallelismtests.proxies.ExampleResult parallel_SendMessage(IContext context)
	{
		Object result = parallel_SendMessageBuilder().execute(context);
		return result == null ? null : parallelismtests.proxies.ExampleResult.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder parallel_WaitingLongBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.Parallel_WaitingLong");
		return builder;
	}

	public static boolean parallel_WaitingLong(IContext context)
	{
		Object result = parallel_WaitingLongBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder parallel_WaitingShortBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.Parallel_WaitingShort");
		return builder;
	}

	public static boolean parallel_WaitingShort(IContext context)
	{
		Object result = parallel_WaitingShortBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sub_ProcessBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.Sub_Process");
		return builder;
	}

	public static void sub_Process(IContext context)
	{
		sub_ProcessBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sub_SetErrorBuilder(
		parallelismtests.proxies.TestOrder _testOrder,
		java.lang.String _errorMessage
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.Sub_SetError");
		builder = builder.withParam("TestOrder", _testOrder);
		builder = builder.withParam("ErrorMessage", _errorMessage);
		return builder;
	}

	public static void sub_SetError(
		IContext context,
		parallelismtests.proxies.TestOrder _testOrder,
		java.lang.String _errorMessage
	)
	{
		sub_SetErrorBuilder(
				_testOrder,
				_errorMessage
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sub_ThrowErrorBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ParallelismTests.Sub_ThrowError");
		return builder;
	}

	public static void sub_ThrowError(IContext context)
	{
		sub_ThrowErrorBuilder().execute(context);
	}
}
