// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package parallelism.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Parallelism module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder beforeShutdownBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Parallelism.BeforeShutdown");
		return builder;
	}

	public static void beforeShutdown(IContext context)
	{
		beforeShutdownBuilder().execute(context);
	}
}
