// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package parallelism.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IUser;
import com.mendix.webui.CustomJavaAction;
import parallelism.implementation.BackgroundMicroflowThread;
import parallelism.implementation.Constants;
import parallelism.implementation.Parallelism;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ExecuteInBackground extends UserAction<java.lang.Boolean>
{
	private final java.lang.Long amountOfThreads;
	private final java.lang.String microflow;
	private final java.lang.Boolean repeat;
	private final java.lang.Long sleep;
	private final java.lang.Boolean sleepWhenFalse;

	public ExecuteInBackground(
		IContext context,
		java.lang.Long _amountOfThreads,
		java.lang.String _microflow,
		java.lang.Boolean _repeat,
		java.lang.Long _sleep,
		java.lang.Boolean _sleepWhenFalse
	)
	{
		super(context);
		this.amountOfThreads = _amountOfThreads;
		this.microflow = _microflow;
		this.repeat = _repeat;
		this.sleep = _sleep;
		this.sleepWhenFalse = _sleepWhenFalse;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		for (int i = 0; i < amountOfThreads; i++) {
			Parallelism.addThread(new BackgroundMicroflowThread(microflow, repeat, sleep, sleepWhenFalse, null));
		}
		Constants.LOGNODE.info("Started " + amountOfThreads + " threads invoking " + microflow);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteInBackground";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
